extends SceneTree
## Second test geometry for map independence (IS-106, KR-037): a horizontal mirror of store_a (register/counter, back room, side street
## and escape zone on the opposite side). Generates `tests/fixtures/layouts/store_a_mirror.txt` from levels/layouts/store_a.txt (grid rows
## reversed, unpainted zone rectangles mirrored, marker/zone letters unchanged) and `tests/fixtures/store_a_mirror.tscn` with the level
## generator (`build_levels.gd` `build_scene`, unchanged); the hand-placed part of store_a.tscn (Players, Props, NPCs, EscapeMarker ...)
## is copied with mirrored positions. store_a's own files are only read. Re-run after store_a changes (test_map_independence checks
## the committed mirror is in sync):
##   $GODOT --headless --path . -s res://tests/fixtures/build_mirror.gd

const SRC_LAYOUT := "res://levels/layouts/store_a.txt"
const SRC_SCENE := "res://levels/store_a.tscn"
const OUT_LAYOUT := "res://tests/fixtures/layouts/store_a_mirror.txt"
const OUT_SCENE := "res://tests/fixtures/store_a_mirror.tscn"
const BUILDER := "res://levels/tools/build_levels.gd"
const ROOT_NAME := "StoreAMirror"
## Root children the generator rebuilds (copying them would be overwritten anyway).
const GENERATED: Array[String] = ["Tiles", "Walls", "SpawnPoints", "Markers", "Zones", "Navigation"]
const TILE := 32


func _initialize() -> void:
	var err: Error = build(SRC_LAYOUT, SRC_SCENE, OUT_LAYOUT, OUT_SCENE)
	if err != OK:
		push_error("build_mirror: %s" % error_string(err))
	quit(0 if err == OK else 1)


## Writes the mirrored layout and scene. OK on success.
static func build(src_layout: String, src_scene: String, out_layout: String, out_scene: String) -> Error:
	var text: String = mirror_layout_text(FileAccess.get_file_as_string(src_layout), src_layout.get_file())
	if text.is_empty():
		return ERR_PARSE_ERROR
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(out_layout.get_base_dir()))
	var file := FileAccess.open(out_layout, FileAccess.WRITE)
	if file == null:
		return FileAccess.get_open_error()
	file.store_string(text)
	file.close()
	var width_px: float = float(grid_width(text) * TILE)
	var builder: Script = load(BUILDER) as Script
	var uid_text: String = str(builder.call(&"_header_uid", out_scene))
	var err: Error = _write_kept_part(src_scene, out_scene, width_px)
	if err == OK and not uid_text.is_empty():
		err = builder.call(&"_write_uids", out_scene, uid_text) as Error
	if err == OK:
		err = builder.call(&"build_scene", out_layout, out_scene) as Error
	return err


## Horizontal mirror of a layout file's text: grid rows reversed, `= <Name> <col> <row> <w> <h>` rectangles mirrored, marker/zone letter
## lines kept, comments replaced by a generated-file header. Empty on a malformed grid.
static func mirror_layout_text(src: String, src_name: String) -> String:
	var width: int = grid_width(src)
	if width <= 0:
		return ""
	var out: PackedStringArray = [
		"; store_a_mirror - horizontal mirror of levels/layouts/%s (IS-106 map-independence fixture)." % src_name,
		"; GENERATED by tests/fixtures/build_mirror.gd - do not edit; re-run the tool after store_a changes.",
	]
	for raw: String in src.split("\n"):
		var line: String = raw.strip_edges(false, true)
		if line.is_empty() or line.begins_with(";"):
			continue
		var parts: PackedStringArray = line.split(" ", false)
		if line.begins_with("=") and parts.size() == 6:
			var col: int = width - int(parts[2]) - int(parts[4])
			out.append("= %s %d %s %s %s" % [parts[1], col, parts[3], parts[4], parts[5]])
		elif line.begins_with("@") or line.begins_with("="):
			out.append(line)
		else:
			out.append(line.reverse())
	return "\n".join(out) + "\n"


## Width (tiles) of the layout grid: the first non-comment, non-definition line.
static func grid_width(text: String) -> int:
	for raw: String in text.split("\n"):
		var line: String = raw.strip_edges(false, true)
		if line.is_empty() or line.begins_with(";") or line.begins_with("@") or line.begins_with("="):
			continue
		return line.length()
	return 0


## Mirrored x of a position in a map `width_px` wide.
static func mirror_x(pos: Vector2, width_px: float) -> Vector2:
	return Vector2(width_px - pos.x, pos.y)


## Saves the out scene's root (Level script) with copies of the source's hand-placed root children; the direct children of those
## containers (props, NPCs) and the containers themselves get mirrored positions.
static func _write_kept_part(src_scene: String, out_scene: String, width_px: float) -> Error:
	var packed_src: PackedScene = ResourceLoader.load(src_scene, "", ResourceLoader.CACHE_MODE_IGNORE) as PackedScene
	if packed_src == null:
		return ERR_FILE_CANT_OPEN
	var src: Node2D = packed_src.instantiate(PackedScene.GEN_EDIT_STATE_MAIN) as Node2D
	var root := Node2D.new()
	root.name = ROOT_NAME
	root.set_script(src.get_script())
	for child: Node in src.get_children():
		if GENERATED.has(String(child.name)):
			continue
		var copy: Node = child.duplicate()
		root.add_child(copy)
		_mirror(copy, width_px)
		for sub: Node in copy.get_children():
			_mirror(sub, width_px)
		_own(copy, root)
	var packed := PackedScene.new()
	var err: Error = packed.pack(root)
	if err == OK:
		err = ResourceSaver.save(packed, out_scene)
	root.free()
	src.free()
	return err


static func _mirror(node: Node, width_px: float) -> void:
	var n2d: Node2D = node as Node2D
	if n2d != null and not n2d.position.is_zero_approx():
		n2d.position = mirror_x(n2d.position, width_px)


## Owner = root for the copied subtree; the inside of an instanced sub-scene stays the sub-scene's.
static func _own(node: Node, root: Node) -> void:
	node.owner = root
	if not node.scene_file_path.is_empty():
		return
	for child: Node in node.get_children():
		_own(child, root)
